package de.greenrobot.daoexample;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MUSIC.
 */
public class Music {

    private Long uid;
    public String name;
    private String artist;
    private String cache_url;
    private String url;
    private String lrc_url;
    private String lrc_cache_url;
    private String pic_url;
    private Boolean isLocal;

    public Music() {
    }

    public Music(Long uid) {
        this.uid = uid;
    }

    public Music(Long uid, String name, String artist, String cache_url, String url, String lrc_url, String lrc_cache_url, String pic_url, Boolean isLocal) {
        this.uid = uid;
        this.name = name;
        this.artist = artist;
        this.cache_url = cache_url;
        this.url = url;
        this.lrc_url = lrc_url;
        this.lrc_cache_url = lrc_cache_url;
        this.pic_url = pic_url;
        this.isLocal = isLocal;
    }

    public Long getUid() {
        return uid;
    }

    public void setUid(Long uid) {
        this.uid = uid;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getArtist() {
        return artist;
    }

    public void setArtist(String artist) {
        this.artist = artist;
    }

    public String getCache_url() {
        return cache_url;
    }

    public void setCache_url(String cache_url) {
        this.cache_url = cache_url;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getLrc_url() {
        return lrc_url;
    }

    public void setLrc_url(String lrc_url) {
        this.lrc_url = lrc_url;
    }

    public String getLrc_cache_url() {
        return lrc_cache_url;
    }

    public void setLrc_cache_url(String lrc_cache_url) {
        this.lrc_cache_url = lrc_cache_url;
    }

    public String getPic_url() {
        return pic_url;
    }

    public void setPic_url(String pic_url) {
        this.pic_url = pic_url;
    }

    public Boolean getIsLocal() {
        return isLocal;
    }

    public void setIsLocal(Boolean isLocal) {
        this.isLocal = isLocal;
    }

}
