package de.greenrobot.daoexample;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SYSTEM_MESSAGE.
 */
public class SystemMessage {

    private Long id;
    private Long user_id;
    private Long sender_id;
    private String category;
    private String message;
    private String pic_url;

    public SystemMessage() {
    }

    public SystemMessage(Long id) {
        this.id = id;
    }

    public SystemMessage(Long id, Long user_id, Long sender_id, String category, String message, String pic_url) {
        this.id = id;
        this.user_id = user_id;
        this.sender_id = sender_id;
        this.category = category;
        this.message = message;
        this.pic_url = pic_url;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUser_id() {
        return user_id;
    }

    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }

    public Long getSender_id() {
        return sender_id;
    }

    public void setSender_id(Long sender_id) {
        this.sender_id = sender_id;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public String getPic_url() {
        return pic_url;
    }

    public void setPic_url(String pic_url) {
        this.pic_url = pic_url;
    }

}
